return {
	[1] = {
		["Column4"] = 0,
		["itemType"] = 1,
		["weight"] = 60000,
		["id"] = 1,
		["itemId"] = 1,
	},
	[2] = {
		["Column4"] = 0,
		["itemType"] = 1,
		["weight"] = 23000,
		["id"] = 1,
		["itemId"] = 2,
	},
	[3] = {
		["Column4"] = 0,
		["itemType"] = 1,
		["weight"] = 13200,
		["id"] = 1,
		["itemId"] = 3,
	},
	[4] = {
		["Column4"] = 0,
		["itemType"] = 1,
		["weight"] = 3400,
		["id"] = 1,
		["itemId"] = 4,
	},
	[5] = {
		["Column4"] = 0,
		["itemType"] = 1,
		["weight"] = 375,
		["id"] = 1,
		["itemId"] = 5,
	},
	[6] = {
		["Column4"] = 0,
		["itemType"] = 1,
		["weight"] = 25,
		["id"] = 1,
		["itemId"] = 6,
	},
}