return {
	[1] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 1,
	},
	[2] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 2,
	},
	[3] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 3,
	},
	[4] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 4,
	},
	[5] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 5,
	},
	[6] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 6,
	},
	[7] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 7,
	},
	[8] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 8,
	},
	[9] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 9,
	},
	[10] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 10,
	},
	[11] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 11,
	},
	[12] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 12,
	},
	[13] = {
		["id"] = 1,
		["itemType"] = 1,
		["itemId"] = 13,
	},
	[14] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 14,
	},
	[15] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 15,
	},
	[16] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 16,
	},
	[17] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 17,
	},
	[18] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 18,
	},
	[19] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 19,
	},
	[20] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 20,
	},
	[21] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 21,
	},
	[22] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 22,
	},
	[23] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 23,
	},
	[24] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 24,
	},
	[25] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 25,
	},
	[26] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 26,
	},
	[27] = {
		["id"] = 2,
		["itemType"] = 1,
		["itemId"] = 27,
	},
	[28] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 28,
	},
	[29] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 29,
	},
	[30] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 30,
	},
	[31] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 31,
	},
	[32] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 32,
	},
	[33] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 33,
	},
	[34] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 34,
	},
	[35] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 35,
	},
	[36] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 36,
	},
	[37] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 37,
	},
	[38] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 38,
	},
	[39] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 39,
	},
	[40] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 40,
	},
	[41] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 41,
	},
	[42] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 42,
	},
	[43] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 43,
	},
	[44] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 44,
	},
	[45] = {
		["id"] = 3,
		["itemType"] = 1,
		["itemId"] = 45,
	},
	[46] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 46,
	},
	[47] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 47,
	},
	[48] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 48,
	},
	[49] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 49,
	},
	[50] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 50,
	},
	[51] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 51,
	},
	[52] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 52,
	},
	[53] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 53,
	},
	[54] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 54,
	},
	[55] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 55,
	},
	[56] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 56,
	},
	[57] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 57,
	},
	[58] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 58,
	},
	[59] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 59,
	},
	[60] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 60,
	},
	[61] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 61,
	},
	[62] = {
		["id"] = 4,
		["itemType"] = 1,
		["itemId"] = 62,
	},
}